import { NgModule } from '@angular/core';
import { CommonModule } from '@angular/common';
import { MatButtonModule,
        MatToolbarModule,
        MatInputModule,
        MatProgressSpinnerModule,
        MatCardModule,
        MatSidenavModule,
        MatCheckboxModule,
        MatDividerModule,
        MatListModule,
        MatIconModule,
        MatGridListModule,
        MatTabsModule,
        MatFormFieldModule,
        MatExpansionModule,
        MatMenuModule,
        MatRadioModule,
        MatDatepickerModule,
        MatChipsModule,
        MatAutocompleteModule,
        MatButtonToggleModule,

      MatNativeDateModule,} from '@angular/material';

@NgModule({
  imports: [MatButtonModule,
            MatToolbarModule,
            MatInputModule,
            MatProgressSpinnerModule,
            MatCardModule,
            MatSidenavModule,
            MatCheckboxModule,
            MatDividerModule,
            MatListModule,
            MatIconModule,
            MatGridListModule,
            MatTabsModule,
            MatFormFieldModule,
            MatExpansionModule,
            MatMenuModule,
            MatRadioModule,
            MatDatepickerModule,
            MatNativeDateModule,
            MatChipsModule,
            MatAutocompleteModule,
            MatButtonToggleModule,

          ],
  exports: [MatButtonModule,
            MatToolbarModule,
            MatInputModule,
            MatProgressSpinnerModule,
            MatCardModule,
            MatSidenavModule,
            MatCheckboxModule,
            MatDividerModule,
            MatListModule,
            MatIconModule,
            MatGridListModule,
            MatTabsModule,
            MatFormFieldModule,
            MatExpansionModule,
            MatChipsModule,
            MatMenuModule,
            MatRadioModule,
            MatDatepickerModule,
            MatNativeDateModule,
            MatChipsModule,
            MatAutocompleteModule,
            MatButtonToggleModule,

          ],
})
export class MaterialModule { }
